---
    - name: Installing SCL release
      yum:
        name: centos-release-scl
        state: present
        lock_timeout: 350
        
    - name: Installing HTTPD
      yum:
        name: httpd
        state: present
        lock_timeout: 350

    - name: Installing Mariadb
      yum:
        name: 
          - mariadb-server
          - mariadb
        state: present
        lock_timeout: 350

    - name: Installing PHP 7.3 repository
      yum:
        name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
        state: present
        lock_timeout: 350

    - name: Enabling php73
      shell: yum-config-manager --enable remi-php73

    - name: Installing PHP 7.3 packages 
      yum:
        name:
          - yum-utils
          - php
          - php-mcrypt
          - php-cli
          - php-gd
          - php-curl
          - php-mysql 
          - php-ldap
          - php-zip 
          - php-fileinfo
          - php-xml
          - php-intl
          - MySQL-python
          - rh-php73
          - rh-php73-php
          - rh-php73-php-mbstring
          - rh-php73-php-mysqlnd
          - rh-php73-php-gd
          - rh-php73-php-xml
          - mysql
        state: present
        lock_timeout: 350

    - name: Installing PyMySQL
      shell: pip3 install PyMySQL
        